
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer   #POD olusurken bunu cleim bagliyor. immediate direk bagliyor buda fiyat olusturuyor.
parameters:
  type: gp2
  fsType: ext4


