
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ahmet-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: aws-standard            #Hangisinden talep ediyoruz ismini yaziyoruz.



